
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        
        app: postgres-container
        
        tier: backend
    spec:
      containers:
        - name: postgres-container
         
          image: postgres:9.6.6
          env:
            - name: POSTGRES_USER #Referencia al valor de secret.yaml
              valueFrom:
                secretKeyRef:
                  name: db-conf
                  key: usuario

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-conf
                  key: password

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap-fa-pg
                  key: dbname

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc